"""Changed roasted coffees logic, now is independent of inventory

Revision ID: 2218c54b0873
Revises: 58f4918c085e
Create Date: 2026-06-14 12:32:08.287218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2218c54b0873'
down_revision: Union[str, Sequence[str], None] = '58f4918c085e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roasted_coffees', sa.Column('quantity', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('roasted_coffees', sa.Column('remaining_quantity', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('roasted_coffees', 'observations',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_inventory_id'), table_name='roasted_coffees')
    op.drop_index(op.f('idx_product_id'), table_name='roasted_coffees')
    op.drop_constraint(op.f('roasted_coffees_inventory_id_key'), 'roasted_coffees', type_='unique')
    op.drop_constraint(op.f('roasted_coffees_product_id_fkey'), 'roasted_coffees', type_='foreignkey')
    op.drop_constraint(op.f('roasted_coffees_inventory_id_fkey'), 'roasted_coffees', type_='foreignkey')
    op.drop_column('roasted_coffees', 'inventory_id')
    op.drop_column('roasted_coffees', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roasted_coffees', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('roasted_coffees', sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('roasted_coffees_inventory_id_fkey'), 'roasted_coffees', 'inventories', ['inventory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('roasted_coffees_product_id_fkey'), 'roasted_coffees', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('roasted_coffees_inventory_id_key'), 'roasted_coffees', ['inventory_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_product_id'), 'roasted_coffees', ['product_id'], unique=False)
    op.create_index(op.f('idx_inventory_id'), 'roasted_coffees', ['inventory_id'], unique=False)
    op.alter_column('roasted_coffees', 'observations',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('roasted_coffees', 'remaining_quantity')
    op.drop_column('roasted_coffees', 'quantity')
    # ### end Alembic commands ###
