"""add_fairs_module

Revision ID: 261693760453
Revises: c147cfdcf7f8
Create Date: 2026-07-01 23:38:19.306122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261693760453'
down_revision: Union[str, Sequence[str], None] = 'c147cfdcf7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new values to MovementTypeEnum (PostgreSQL requires explicit ALTER TYPE)
    op.execute("ALTER TYPE movementtypeenum ADD VALUE IF NOT EXISTS 'fair_entrance'")
    op.execute("ALTER TYPE movementtypeenum ADD VALUE IF NOT EXISTS 'fair_return'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='fairstatusenum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fair_start', 'fairs', ['start_datetime'], unique=False)
    op.create_index('idx_fair_status', 'fairs', ['status'], unique=False)
    op.create_index('idx_fair_user_id', 'fairs', ['user_id'], unique=False)
    op.create_table('fair_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fair_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('food', 'supplies', 'transport', 'other', name='expensecategoryenum'), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fair_id'], ['fairs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fair_exp_fair_id', 'fair_expenses', ['fair_id'], unique=False)
    op.create_table('fair_inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fair_id', sa.Integer(), nullable=False),
    sa.Column('detail_roasted_coffee_id', sa.Integer(), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['detail_roasted_coffee_id'], ['detail_roasted_coffees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fair_id'], ['fairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fair_inv_drc_id', 'fair_inventories', ['detail_roasted_coffee_id'], unique=False)
    op.create_index('idx_fair_inv_fair_id', 'fair_inventories', ['fair_id'], unique=False)
    op.create_table('fair_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fair_id', sa.Integer(), nullable=False),
    sa.Column('fair_inventory_id', sa.Integer(), nullable=False),
    sa.Column('sale_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fair_id'], ['fairs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fair_inventory_id'], ['fair_inventories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fair_sale_datetime', 'fair_sales', ['sale_datetime'], unique=False)
    op.create_index('idx_fair_sale_fair_id', 'fair_sales', ['fair_id'], unique=False)
    op.create_index('idx_fair_sale_inv_id', 'fair_sales', ['fair_inventory_id'], unique=False)
    op.add_column('inventory_movements', sa.Column('fair_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_movements', 'fairs', ['fair_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sales', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'fair_id')
    op.drop_index('idx_fair_sale_inv_id', table_name='fair_sales')
    op.drop_index('idx_fair_sale_fair_id', table_name='fair_sales')
    op.drop_index('idx_fair_sale_datetime', table_name='fair_sales')
    op.drop_table('fair_sales')
    op.drop_index('idx_fair_inv_fair_id', table_name='fair_inventories')
    op.drop_index('idx_fair_inv_drc_id', table_name='fair_inventories')
    op.drop_table('fair_inventories')
    op.drop_index('idx_fair_exp_fair_id', table_name='fair_expenses')
    op.drop_table('fair_expenses')
    op.drop_index('idx_fair_user_id', table_name='fairs')
    op.drop_index('idx_fair_status', table_name='fairs')
    op.drop_index('idx_fair_start', table_name='fairs')
    op.drop_table('fairs')
    # ### end Alembic commands ###
