"""add_sale_id_to_inventory_movements

Revision ID: 31d15787710c
Revises: f5c9531347fa
Create Date: 2026-07-01 21:29:35.110016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d15787710c'
down_revision: Union[str, Sequence[str], None] = 'f5c9531347fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_movements', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'sale_id')
    # ### end Alembic commands ###
