"""create roasted table with back populates on others tables

Revision ID: 58f4918c085e
Revises: 4f2c8c91a1b3
Create Date: 2026-06-13 20:06:40.183591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f4918c085e'
down_revision: Union[str, Sequence[str], None] = '4f2c8c91a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roasted_coffees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id')
    )
    op.create_index('idx_inventory_id', 'roasted_coffees', ['inventory_id'], unique=False)
    op.create_index('idx_process_id', 'roasted_coffees', ['process_id'], unique=False)
    op.create_index('idx_product_id', 'roasted_coffees', ['product_id'], unique=False)
    op.drop_column('products', 'presentation_grams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('presentation_grams', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('idx_product_id', table_name='roasted_coffees')
    op.drop_index('idx_process_id', table_name='roasted_coffees')
    op.drop_index('idx_inventory_id', table_name='roasted_coffees')
    op.drop_table('roasted_coffees')
    # ### end Alembic commands ###
