"""The last migration was error, i put the relation on products table when it was on users, now it is on users

Revision ID: 674f8dbc90fa
Revises: 44ed6258a81e
Create Date: 2026-04-25 18:00:38.614060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674f8dbc90fa'
down_revision: Union[str, Sequence[str], None] = '44ed6258a81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
