"""add_roasted_movements

Revision ID: 82a68a9718aa
Revises: 261693760453
Create Date: 2026-07-02 12:02:51.037272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a68a9718aa'
down_revision: Union[str, Sequence[str], None] = '261693760453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roasted_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roasted_movement_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('detail_roasted_coffee_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detail_roasted_coffee_id'], ['detail_roasted_coffees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['roasted_movements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roasted_movement_details')
    op.drop_table('roasted_movements')
    # ### end Alembic commands ###
