"""Changed on products type on model of products add other option

Revision ID: f37526f799dc
Revises: dbedcab4b3b9
Create Date: 2026-04-17 12:41:51.574903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37526f799dc'
down_revision: Union[str, Sequence[str], None] = 'dbedcab4b3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("ALTER TYPE producttypeenum ADD VALUE 'other'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
