"""add_sales_and_detail_sales

Revision ID: f5c9531347fa
Revises: af6c41c2ca15
Create Date: 2026-07-01 21:23:35.943482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PgEnum


# revision identifiers, used by Alembic.
revision: str = 'f5c9531347fa'
down_revision: Union[str, Sequence[str], None] = 'af6c41c2ca15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = PgEnum('completed', 'in_progress', name='salestatusenum', create_type=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_customer_id', 'sales', ['customer_id'], unique=False)
    op.create_index('idx_sale_date', 'sales', ['sale_date'], unique=False)
    op.create_index('idx_sale_status', 'sales', ['status'], unique=False)
    op.create_index('idx_sale_user_id', 'sales', ['user_id'], unique=False)
    op.create_table('detail_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('detail_roasted_coffee_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['detail_roasted_coffee_id'], ['detail_roasted_coffees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detail_sale_drc_id', 'detail_sales', ['detail_roasted_coffee_id'], unique=False)
    op.create_index('idx_detail_sale_sale_id', 'detail_sales', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_detail_sale_sale_id', table_name='detail_sales')
    op.drop_index('idx_detail_sale_drc_id', table_name='detail_sales')
    op.drop_table('detail_sales')
    op.drop_index('idx_sale_user_id', table_name='sales')
    op.drop_index('idx_sale_status', table_name='sales')
    op.drop_index('idx_sale_date', table_name='sales')
    op.drop_index('idx_sale_customer_id', table_name='sales')
    op.drop_table('sales')
    sa.Enum(name='salestatusenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
