"""Changed roasted coffees logic, now has a details for the products

Revision ID: 3b54dbf31579
Revises: 2218c54b0873
Create Date: 2026-06-14 13:11:39.921234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b54dbf31579'
down_revision: Union[str, Sequence[str], None] = '2218c54b0873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_roasted_coffees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roasted_coffee_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roasted_coffee_id'], ['roasted_coffees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_id', 'detail_roasted_coffees', ['product_id'], unique=False)
    op.create_index('idx_roasted_coffee_id', 'detail_roasted_coffees', ['roasted_coffee_id'], unique=False)
    op.drop_column('roasted_coffees', 'remaining_quantity')
    op.drop_column('roasted_coffees', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roasted_coffees', sa.Column('quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('roasted_coffees', sa.Column('remaining_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index('idx_roasted_coffee_id', table_name='detail_roasted_coffees')
    op.drop_index('idx_product_id', table_name='detail_roasted_coffees')
    op.drop_table('detail_roasted_coffees')
    # ### end Alembic commands ###
