"""Changed values of farmers, added village and municipality

Revision ID: 3ca21f8173e0
Revises: 66fe61cfae96
Create Date: 2026-04-15 16:18:42.359170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca21f8173e0'
down_revision: Union[str, Sequence[str], None] = '66fe61cfae96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Crear como nullable
    op.add_column('farmers', sa.Column('village', sa.String(length=255), nullable=True))
    op.add_column('farmers', sa.Column('municipality', sa.String(length=255), nullable=True))

    # 2. Poblar datos existentes (elige bien este valor)
    op.execute("UPDATE farmers SET village = 'Sin definir' WHERE village IS NULL;")
    op.execute("UPDATE farmers SET municipality = 'Sin definir' WHERE municipality IS NULL;")

    # 3. Ahora sí, hacer NOT NULL
    op.alter_column('farmers', 'village', nullable=False)
    op.alter_column('farmers', 'municipality', nullable=False)

    # 4. Eliminar columna vieja
    op.drop_column('farmers', 'farm_location')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('farm_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('farmers', 'municipality')
    op.drop_column('farmers', 'village')
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
