"""add relation to user on fast sales table

Revision ID: 44ed6258a81e
Revises: 8f189c48dede
Create Date: 2026-04-25 17:49:31.428190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ed6258a81e'
down_revision: Union[str, Sequence[str], None] = '8f189c48dede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fast_sales', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fast_sales', 'users', ['user_id'], ['id'])
    op.drop_column('fast_sales', 'seller')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fast_sales', sa.Column('seller', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fast_sales', type_='foreignkey')
    op.drop_column('fast_sales', 'user_id')
    # ### end Alembic commands ###
