"""Changed inventory movements field (processed_id) to (processes_id) changed relationship of tables

Revision ID: a24bcd5c43e1
Revises: 3b54dbf31579
Create Date: 2026-06-15 13:55:48.144886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24bcd5c43e1'
down_revision: Union[str, Sequence[str], None] = '3b54dbf31579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('process_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('inventory_movements_processed_id_fkey'), 'inventory_movements', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_movements', 'processes', ['process_id'], ['id'], ondelete='CASCADE')
    op.drop_column('inventory_movements', 'processed_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('processed_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_movements_processed_id_fkey'), 'inventory_movements', 'processed', ['processed_id'], ['id'], ondelete='CASCADE')
    op.drop_column('inventory_movements', 'process_id')
    # ### end Alembic commands ###
