"""Changed products values, added quantity and added one other type

Revision ID: dbedcab4b3b9
Revises: 3ca21f8173e0
Create Date: 2026-04-17 11:35:26.397332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbedcab4b3b9'
down_revision: Union[str, Sequence[str], None] = '3ca21f8173e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Crear columna permitiendo NULL
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))

    # 2. Rellenar datos existentes (ejemplo: 0)
    op.execute("UPDATE products SET quantity = 0")

    # 3. Hacerla NOT NULL
    op.alter_column('products', 'quantity', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
